wget -P mmarco/raw/collections https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/collections/vietnamese_collection.tsv
wget -P mmarco/raw/collections https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/collections/english_collection.tsv
wget -P mmarco/raw/queries https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/queries/train/vietnamese_queries.train.tsv
wget -P mmarco/raw/queries https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/queries/train/english_queries.train.tsv
wget -P mmarco/raw/queries https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/queries/dev/vietnamese_queries.dev.tsv
wget -P mmarco/raw/queries https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/queries/dev/english_queries.dev.tsv
wget -P mmarco/raw/runs https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/runs/run.bm25_vietnamese-msmarco.txt
wget -P mmarco/raw/runs https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/google/runs/run.bm25_english-msmarco.txt
wget -P mmarco/raw https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/triples.train.ids.small.tsv
wget -P mmarco/raw https://huggingface.co/datasets/unicamp-dl/mmarco/resolve/main/data/qrels.dev.tsv